### PR TITLE
Store the `Store` instance itself in the context data

### LINKED ISSUE #200: `Function` instance passed to a callback (as `funcref`) cannot be called outside of the callback
Currently, when a callback gets a `funcref` value, it will be created as a `Function` instance, using the `Caller` as `IStore`. However, the `Caller` is only valid within the callback, so it's not possible to store the `Function` and later call it outside of the callback.

Consider the following code:
```cs
using var engine = new Engine();
using var module1 = Module.FromText(
    engine,
    "hello",
    @"
(module 
    (import """" ""store_funcref"" (func $store_funcref (param funcref)))
    (export ""run"" (func $run))
    (elem declare func $getValue)
    (func $getValue (result i32)
        i32.const 123
    )
    (func $run 
        (call $store_funcref (ref.func $getValue))
    )
)");

using var linker = new Linker(engine);
using var store = new Store(engine);

var storedFuncRef = default(Function);
linker.DefineFunction("", "store_funcref", (Function? funcRef) =>
{
    storedFuncRef = funcRef;
});

var instance = linker.Instantiate(store, module1);

var run = instance.GetAction("run")!;
run();

var wrappedFuncRef = storedFuncRef!.WrapFunc<int>()!;
int result = wrappedFuncRef();
Console.WriteLine("Result: " + result);
```

**Expected behavior:**

Runs successfully and prints `Result: 123` to the console.

**Actual behavior:**

Throws an `ObjectDisposedException`, because the `Caller` is no longer usable.
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Wasmtime.Caller'.
   at Wasmtime.Caller.get_NativeHandle() in C:\Users\VPC\Desktop\WebAssembly-Test\wasmtime-dotnet\src\Caller.cs:line 92
   at Wasmtime.Caller.Wasmtime.IStore.get_Context() in C:\Users\VPC\Desktop\WebAssembly-Test\wasmtime-dotnet\src\Caller.cs:line 99
   at Wasmtime.Function.<>c__DisplayClass184_0`1.<WrapFunc>b__0() in C:\Users\VPC\Desktop\WebAssembly-Test\wasmtime-dotnet\src\Function.Wrap.cs:line 841
   at Program.<<Main>$>g__TestCallbackStoreFuncRef|0_9() in C:\Users\VPC\Desktop\WebAssembly-Test\TestWasmtime\Program.cs:line 669
   at Program.<Main>$(String[] args) in C:\Users\VPC\Desktop\WebAssembly-Test\TestWasmtime\Program.cs:line 687
```

<del>With the work done by #191, I was thinking to leverage the store data feature, and instead of storing the store's `Data` object, store the `Store` object itself in the context data, so that we can retrieve it from the caller and can use it to create `Function` instances that are still usable outside of the callback.</del>

### PR DESCRIPTION
**Pull request by kpreisser**
Store the `Store` instance itself in the context data using a weak `GCHandle`, so that it can be retrieved later from the `Caller.Store` property.

By using a **weak** `GCHandle`, we avoid the issue that the circular reference between the `Store` and the `GCHandle` would prevent the `Store` from being GCed if it's no longer reachable from user code.

Additionally (as suggested in https://github.com/bytecodealliance/wasmtime-dotnet/issues/200#issuecomment-1401167856), remove the `IStore` interface and change the corresponding method/constructor parameters to accept a `Store` instead.

For example, this allows to create a `funcref` value as `Function` using the associated `Store` instead of the `Caller`, so that it can be stored and then called outside of the callback.

**Note:** Users that previously passed a `Caller` instance to a method accepting an `IStore` will now need to use `caller.Store`.

This is a remake of the earlier PR, #201.

Fixes #200

What do you think?
Thanks!

### CODE REVIEW

File: src/Store.cs [hunk 1]
```diff
@@ -28,32 +28,20 @@ internal void AddFuel(ulong fuel)
...
-            }
+                var data = Native.wasmtime_context_get_data(handle);
 
-            Native.wasmtime_context_set_data(handle, newPtr);
+                // Since this is a weak handle, it could be `null` if the target object (`Store`)
+                // was already collected. However, this would be an error in wasmtime-dotnet
+                // itself because the `Store` must be kept alive when this is called, and
+                // therefore this shouldn't happen.
+                var targetStore = (Store?)GCHandle.FromIntPtr(data).Target ??
+                    throw new ObjectDisposedException(nameof(Wasmtime.Store));
```
Comment (kpreisser) [inline src/Store.cs:42]: Thinking more about this, I think the check for `null` here (and throwing in that case) probably doesn't make much sense because if the `Store` would actually have been GCed, its `Handle` might also already have been deleted, which in turn would have freed the `GCHandle`, and thus it would already be invalid (leading to UB) to try to retrieve the `GCHandle` from the `IntPtr` value in such a case.

Comment (kpreisser) [reply src/Store.cs]: I removed the null check here.

**Review by peterhuene — APPROVED** [review]
This looks good, I'm happy with were we landed with this.

@martindevans would you also mind reviewing to see how this impacts #210?

**Comment by martindevans** [comment]
It looks good to me 👍 

If you go ahead with merging this then I'd suggest simply closing #210 for now - this changes the landscape enough that it'll be eaisest for me to just reimplement everything on top of it.

**Comment by peterhuene** [comment]
@martindevans do you think you'd be able to replace #210 today? I am hoping to clear out the PR queue and cut some releases that are long overdue.

**Comment by martindevans** [comment]
I'll give it a go. I think this should significantly simplify things, so hopefully I can get it done within an hour or two. If it looks like it's going to be more complex and I can't get it done within that window I'll comment on #210.

**Comment by peterhuene** [comment]
@martindevans Thanks, very much appreciated!

**Comment by martindevans** [comment]
Ah I think this may have a bug, apologies for not catching it before the merge. It looks like it fails one of my new Caller tests (introduced in #209).

This test triggers an access violation exception:

```csharp
[Fact]
public void ItCannotBeAccessedAfterDisposal()
{
    Caller stash = default;

    Linker.DefineFunction("env", "callback", (Caller c) =>
    {
        stash = c;
    });

    var instance = Linker.Instantiate(Store, Fixture.Module);
    var callback = instance.GetFunction("call_callback")!;

    callback.Invoke();

    var act = () => stash.GetMemory("memory");
    act.Should().Throw<ObjectDisposedException>();
}
```

Dispose is called internally but of course I've already stashed away a _copy_ before that happens, so that `Caller` now has invalid state.

If no one else has any other solutions I can fix this by adding back in my epoch based mechanism?

**Comment by kpreisser** [comment]
Hi @martindevans,
I'm not sure if I understand the issue; do you mean that when the `Caller` is changed to a `struct` instead of a `class`, the access violation may happen?

Currently, in `main` with the latest commit (43a5b51), `Caller` is still a class, and therefore when the callback returns, it should set its `Handle` to `IntPtr.Zero`, so that when later calling `stash.GetMemory(...)`, it should throw an `ObjectDisposedException`, which seems also to happen for me (as the tests pass).

Thanks!

**Comment by martindevans** [comment]
> I'm not sure if I understand the issue; do you mean that when the Caller is changed to a struct instead of a class, the access violation may happen?

Derp, that's why CI didn't catch it, because it's my own bug. Sorry 🤦‍♂️
